[package]
name = "knx-client"
version = "0.1.0"
authors = ["pitschr <github@pitschmann.li>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
regex = "1.4.6"
colored = "2.0.0"