name: Publish KNX Link Server

on:
  push:
    tags:
      - 'knx-link-server-*' # matches 1, 1.1, 1.1.1, etc.

jobs:
  publish-knx-client:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Publish KNX Link Server

    steps:
      # Gets the tag name (e.g. knx-server-1.0.0)
      - name: Get Tag Name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out
        uses: actions/checkout@v2

      # Uses the Cache for Maven
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Uses JDK 11 for compilation
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # Compile & Test
      - name: Compile & Test
        run: mvn clean package -B -P github-actions

      # Upload the fat JAR package
      - name: Upload KNX Link Server
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/knx-server.jar
          asset_name: ${{ env.RELEASE_VERSION }}.jar
          tag: ${{ github.ref }}
